#!/bin/sh

# build.sh
# 
#
# Created by Mhr on 17/02/2012.
# Copyright 2012 University of Wales, Aberystwyth. All rights reserved.

g++ second_site.cpp ../DNAfind.cpp ../sequence_utils.cpp ../dimerisation.cpp -o second_site
